version: "3"
services:
  mysql:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./infrastructure/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    container_name: clean-go-mysql
    network_mode: "bridge"

